services:
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: urlshortener
      MARIADB_USER: urlshortener_user
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    

